<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    public function run()
    {
        $cities = [
            // 1. Aceh
            ['province_id' => 1, 'name' => 'Aceh Barat'],
            ['province_id' => 1, 'name' => 'Aceh Barat Daya'],
            ['province_id' => 1, 'name' => 'Aceh Besar'],
            ['province_id' => 1, 'name' => 'Aceh Jaya'],
            ['province_id' => 1, 'name' => 'Aceh Selatan'],
            ['province_id' => 1, 'name' => 'Aceh Singkil'],
            ['province_id' => 1, 'name' => 'Aceh Tamiang'],
            ['province_id' => 1, 'name' => 'Aceh Tengah'],
            ['province_id' => 1, 'name' => 'Aceh Tenggara'],
            ['province_id' => 1, 'name' => 'Aceh Timur'],
            ['province_id' => 1, 'name' => 'Aceh Utara'],
            ['province_id' => 1, 'name' => 'Bener Meriah'],
            ['province_id' => 1, 'name' => 'Bireuen'],
            ['province_id' => 1, 'name' => 'Gayo Lues'],
            ['province_id' => 1, 'name' => 'Nagan Raya'],
            ['province_id' => 1, 'name' => 'Pidie'],
            ['province_id' => 1, 'name' => 'Pidie Jaya'],
            ['province_id' => 1, 'name' => 'Simeulue'],
            ['province_id' => 1, 'name' => 'Banda Aceh'],
            ['province_id' => 1, 'name' => 'Langsa'],
            ['province_id' => 1, 'name' => 'Lhokseumawe'],
            ['province_id' => 1, 'name' => 'Sabang'],
            ['province_id' => 1, 'name' => 'Subulussalam'],

            // 2. Sumatera Utara
            ['province_id' => 2, 'name' => 'Asahan'],
            ['province_id' => 2, 'name' => 'Batu Bara'],
            ['province_id' => 2, 'name' => 'Dairi'],
            ['province_id' => 2, 'name' => 'Deli Serdang'],
            ['province_id' => 2, 'name' => 'Humbang Hasundutan'],
            ['province_id' => 2, 'name' => 'Karo'],
            ['province_id' => 2, 'name' => 'Labuhanbatu'],
            ['province_id' => 2, 'name' => 'Labuhanbatu Selatan'],
            ['province_id' => 2, 'name' => 'Labuhanbatu Utara'],
            ['province_id' => 2, 'name' => 'Langkat'],
            ['province_id' => 2, 'name' => 'Mandailing Natal'],
            ['province_id' => 2, 'name' => 'Nias'],
            ['province_id' => 2, 'name' => 'Nias Barat'],
            ['province_id' => 2, 'name' => 'Nias Selatan'],
            ['province_id' => 2, 'name' => 'Nias Utara'],
            ['province_id' => 2, 'name' => 'Padang Lawas'],
            ['province_id' => 2, 'name' => 'Padang Lawas Utara'],
            ['province_id' => 2, 'name' => 'Pakpak Bharat'],
            ['province_id' => 2, 'name' => 'Samosir'],
            ['province_id' => 2, 'name' => 'Serdang Bedagai'],
            ['province_id' => 2, 'name' => 'Simalungun'],
            ['province_id' => 2, 'name' => 'Tapanuli Selatan'],
            ['province_id' => 2, 'name' => 'Tapanuli Tengah'],
            ['province_id' => 2, 'name' => 'Tapanuli Utara'],
            ['province_id' => 2, 'name' => 'Toba'],
            ['province_id' => 2, 'name' => 'Binjai'],
            ['province_id' => 2, 'name' => 'Gunungsitoli'],
            ['province_id' => 2, 'name' => 'Medan'],
            ['province_id' => 2, 'name' => 'Padangsidimpuan'],
            ['province_id' => 2, 'name' => 'Pematangsiantar'],
            ['province_id' => 2, 'name' => 'Sibolga'],
            ['province_id' => 2, 'name' => 'Tanjungbalai'],
            ['province_id' => 2, 'name' => 'Tebing Tinggi'],

            // 3. Sumatera Barat
            ['province_id' => 3, 'name' => 'Agam'],
            ['province_id' => 3, 'name' => 'Dharmasraya'],
            ['province_id' => 3, 'name' => 'Kepulauan Mentawai'],
            ['province_id' => 3, 'name' => 'Lima Puluh Kota'],
            ['province_id' => 3, 'name' => 'Padang Pariaman'],
            ['province_id' => 3, 'name' => 'Pasaman'],
            ['province_id' => 3, 'name' => 'Pasaman Barat'],
            ['province_id' => 3, 'name' => 'Pesisir Selatan'],
            ['province_id' => 3, 'name' => 'Sijunjung'],
            ['province_id' => 3, 'name' => 'Solok'],
            ['province_id' => 3, 'name' => 'Solok Selatan'],
            ['province_id' => 3, 'name' => 'Tanah Datar'],
            ['province_id' => 3, 'name' => 'Bukittinggi'],
            ['province_id' => 3, 'name' => 'Padang'],
            ['province_id' => 3, 'name' => 'Padangpanjang'],
            ['province_id' => 3, 'name' => 'Pariaman'],
            ['province_id' => 3, 'name' => 'Payakumbuh'],
            ['province_id' => 3, 'name' => 'Sawahlunto'],
            ['province_id' => 3, 'name' => 'Solok'],

            // 4. Riau
            ['province_id' => 4, 'name' => 'Bengkalis'],
            ['province_id' => 4, 'name' => 'Indragiri Hilir'],
            ['province_id' => 4, 'name' => 'Indragiri Hulu'],
            ['province_id' => 4, 'name' => 'Kampar'],
            ['province_id' => 4, 'name' => 'Kepulauan Meranti'],
            ['province_id' => 4, 'name' => 'Kuantan Singingi'],
            ['province_id' => 4, 'name' => 'Pelalawan'],
            ['province_id' => 4, 'name' => 'Rokan Hilir'],
            ['province_id' => 4, 'name' => 'Rokan Hulu'],
            ['province_id' => 4, 'name' => 'Siak'],
            ['province_id' => 4, 'name' => 'Dumai'],
            ['province_id' => 4, 'name' => 'Pekanbaru'],

            // 5. Kepulauan Riau
            ['province_id' => 5, 'name' => 'Bintan'],
            ['province_id' => 5, 'name' => 'Karimun'],
            ['province_id' => 5, 'name' => 'Kepulauan Anambas'],
            ['province_id' => 5, 'name' => 'Lingga'],
            ['province_id' => 5, 'name' => 'Natuna'],
            ['province_id' => 5, 'name' => 'Batam'],
            ['province_id' => 5, 'name' => 'Tanjung Pinang'],

            // 6. Jambi
            ['province_id' => 6, 'name' => 'Batanghari'],
            ['province_id' => 6, 'name' => 'Bungo'],
            ['province_id' => 6, 'name' => 'Kerinci'],
            ['province_id' => 6, 'name' => 'Merangin'],
            ['province_id' => 6, 'name' => 'Muaro Jambi'],
            ['province_id' => 6, 'name' => 'Sarolangun'],
            ['province_id' => 6, 'name' => 'Tanjung Jabung Barat'],
            ['province_id' => 6, 'name' => 'Tanjung Jabung Timur'],
            ['province_id' => 6, 'name' => 'Tebo'],
            ['province_id' => 6, 'name' => 'Jambi'],
            ['province_id' => 6, 'name' => 'Sungai Penuh'],

            // 7. Bengkulu
            ['province_id' => 7, 'name' => 'Bengkulu Selatan'],
            ['province_id' => 7, 'name' => 'Bengkulu Tengah'],
            ['province_id' => 7, 'name' => 'Bengkulu Utara'],
            ['province_id' => 7, 'name' => 'Kaur'],
            ['province_id' => 7, 'name' => 'Kepahiang'],
            ['province_id' => 7, 'name' => 'Lebong'],
            ['province_id' => 7, 'name' => 'Mukomuko'],
            ['province_id' => 7, 'name' => 'Rejang Lebong'],
            ['province_id' => 7, 'name' => 'Seluma'],
            ['province_id' => 7, 'name' => 'Bengkulu'],

            // 8. Sumatera Selatan
            ['province_id' => 8, 'name' => 'Banyuasin'],
            ['province_id' => 8, 'name' => 'Empat Lawang'],
            ['province_id' => 8, 'name' => 'Lahat'],
            ['province_id' => 8, 'name' => 'Muara Enim'],
            ['province_id' => 8, 'name' => 'Musi Banyuasin'],
            ['province_id' => 8, 'name' => 'Musi Rawas'],
            ['province_id' => 8, 'name' => 'Musi Rawas Utara'],
            ['province_id' => 8, 'name' => 'Ogan Ilir'],
            ['province_id' => 8, 'name' => 'Ogan Komering Ilir'],
            ['province_id' => 8, 'name' => 'Ogan Komering Ulu'],
            ['province_id' => 8, 'name' => 'Ogan Komering Ulu Selatan'],
            ['province_id' => 8, 'name' => 'Ogan Komering Ulu Timur'],
            ['province_id' => 8, 'name' => 'Penukal Abab Lematang Ilir'],
            ['province_id' => 8, 'name' => 'Lubuklinggau'],
            ['province_id' => 8, 'name' => 'Pagar Alam'],
            ['province_id' => 8, 'name' => 'Palembang'],
            ['province_id' => 8, 'name' => 'Prabumulih'],

            // 9. Kepulauan Bangka Belitung
            ['province_id' => 9, 'name' => 'Bangka'],
            ['province_id' => 9, 'name' => 'Bangka Barat'],
            ['province_id' => 9, 'name' => 'Bangka Selatan'],
            ['province_id' => 9, 'name' => 'Bangka Tengah'],
            ['province_id' => 9, 'name' => 'Belitung'],
            ['province_id' => 9, 'name' => 'Belitung Timur'],
            ['province_id' => 9, 'name' => 'Pangkal Pinang'],

            //10. Provinsi Lampung
            ['province_id' => 10, 'name' => 'Lampung Barat'],
            ['province_id' => 10, 'name' => 'Lampung Selatan'],
            ['province_id' => 10, 'name' => 'Lampung Tengah'],
            ['province_id' => 10, 'name' => 'Lampung Timur'],
            ['province_id' => 10, 'name' => 'Lampung Utara'],
            ['province_id' => 10, 'name' => 'Mesuji'],
            ['province_id' => 10, 'name' => 'Pesawaran'],
            ['province_id' => 10, 'name' => 'Pesisir Barat'],
            ['province_id' => 10, 'name' => 'Pringsewu'],
            ['province_id' => 10, 'name' => 'Tanggamus'],
            ['province_id' => 10, 'name' => 'Tulang Bawang'],
            ['province_id' => 10, 'name' => 'Tulang Bawang Barat'],
            ['province_id' => 10, 'name' => 'Way Kanan'],

            //11. Provinsi Banten
            ['province_id' => 11, 'name' => 'Lebak'],
            ['province_id' => 11, 'name' => 'Pandeglang'],
            ['province_id' => 11, 'name' => 'Serang'],
            ['province_id' => 11, 'name' => 'Tangerang'],
        
            //12. Provinsi DKI Jakarta
            ['province_id' => 12, 'name' => 'Jakarta Barat'],
            ['province_id' => 12, 'name' => 'Jakarta Pusat'],
            ['province_id' => 12, 'name' => 'Jakarta Selatan'],
            ['province_id' => 12, 'name' => 'Jakarta Timur'],
            ['province_id' => 12, 'name' => 'Jakarta Utara'],
            ['province_id' => 12, 'name' => 'Kepulauan Seribu'],

            //13. Provinsi Jawa Barat
            ['province_id' => 13, 'name' => 'Bandung'],
            ['province_id' => 13, 'name' => 'Bandung Barat'],
            ['province_id' => 13, 'name' => 'Bekasi'],
            ['province_id' => 13, 'name' => 'Bogor'],
            ['province_id' => 13, 'name' => 'Ciamis'],
            ['province_id' => 13, 'name' => 'Cianjur'],
            ['province_id' => 13, 'name' => 'Cirebon'],
            ['province_id' => 13, 'name' => 'Garut'],
            ['province_id' => 13, 'name' => 'Indramayu'],
            ['province_id' => 13, 'name' => 'Karawang'],
            ['province_id' => 13, 'name' => 'Kuningan'],
            ['province_id' => 13, 'name' => 'Majalengka'],
            ['province_id' => 13, 'name' => 'Pangandaran'],
            ['province_id' => 13, 'name' => 'Purwakarta'],
            ['province_id' => 13, 'name' => 'Subang'],
            ['province_id' => 13, 'name' => 'Sukabumi'],
            ['province_id' => 13, 'name' => 'Sumedang'],
            ['province_id' => 13, 'name' => 'Tasikmalaya'],

            //14. Provinsi Jawa Tengah
            ['province_id' => 14, 'name' => 'Banjarnegara'],
            ['province_id' => 14, 'name' => 'Banyumas'],
            ['province_id' => 14, 'name' => 'Batang'],
            ['province_id' => 14, 'name' => 'Blora'],
            ['province_id' => 14, 'name' => 'Boyolali'],
            ['province_id' => 14, 'name' => 'Brebes'],
            ['province_id' => 14, 'name' => 'Cilacap'],
            ['province_id' => 14, 'name' => 'Demak'],
            ['province_id' => 14, 'name' => 'Grobogan'],
            ['province_id' => 14, 'name' => 'Jepara'],
            ['province_id' => 14, 'name' => 'Karanganyar'],
            ['province_id' => 14, 'name' => 'Kebumen'],
            ['province_id' => 14, 'name' => 'Kendal'],
            ['province_id' => 14, 'name' => 'Klaten'],
            ['province_id' => 14, 'name' => 'Kudus'],
            ['province_id' => 14, 'name' => 'Magelang'],
            ['province_id' => 14, 'name' => 'Pati'],
            ['province_id' => 14, 'name' => 'Pekalongan'],
            ['province_id' => 14, 'name' => 'Pemalang'],
            ['province_id' => 14, 'name' => 'Purbalingga'],
            ['province_id' => 14, 'name' => 'Purworejo'],
            ['province_id' => 14, 'name' => 'Rembang'],
            ['province_id' => 14, 'name' => 'Semarang'],
            ['province_id' => 14, 'name' => 'Sragen'],
            ['province_id' => 14, 'name' => 'Sukoharjo'],
            ['province_id' => 14, 'name' => 'Tegal'],
            ['province_id' => 14, 'name' => 'Temanggung'],
            ['province_id' => 14, 'name' => 'Wonogiri'],
            ['province_id' => 14, 'name' => 'Wonosobo'],

            //15. Provinsi DI Yogyakarta
            ['province_id' => 15, 'name' => 'Bantul'],
            ['province_id' => 15, 'name' => 'Gunungkidul'],
            ['province_id' => 15, 'name' => 'Kulon Progo'],
            ['province_id' => 15, 'name' => 'Sleman'],

            //16. Provinsi Jawa Timur
            ['province_id' => 16, 'name' => 'Bangkalan'],
            ['province_id' => 16, 'name' => 'Banyuwangi'],
            ['province_id' => 16, 'name' => 'Blitar'],
            ['province_id' => 16, 'name' => 'Bojonegoro'],
            ['province_id' => 16, 'name' => 'Bondowoso'],
            ['province_id' => 16, 'name' => 'Gresik'],
            ['province_id' => 16, 'name' => 'Jember'],
            ['province_id' => 16, 'name' => 'Jombang'],
            ['province_id' => 16, 'name' => 'Kediri'],
            ['province_id' => 16, 'name' => 'Lamongan'],
            ['province_id' => 16, 'name' => 'Lumajang'],
            ['province_id' => 16, 'name' => 'Madiun'],
            ['province_id' => 16, 'name' => 'Magetan'],
            ['province_id' => 16, 'name' => 'Malang'],
            ['province_id' => 16, 'name' => 'Mojokerto'],
            ['province_id' => 16, 'name' => 'Nganjuk'],
            ['province_id' => 16, 'name' => 'Ngawi'],
            ['province_id' => 16, 'name' => 'Pacitan'],
            ['province_id' => 16, 'name' => 'Pamekasan'],
            ['province_id' => 16, 'name' => 'Pasuruan'],
            ['province_id' => 16, 'name' => 'Ponorogo'],
            ['province_id' => 16, 'name' => 'Probolinggo'],
            ['province_id' => 16, 'name' => 'Sampang'],
            ['province_id' => 16, 'name' => 'Sidoarjo'],
            ['province_id' => 16, 'name' => 'Situbondo'],
            ['province_id' => 16, 'name' => 'Sumenep'],
            ['province_id' => 16, 'name' => 'Trenggalek'],
            ['province_id' => 16, 'name' => 'Tuban'],
            ['province_id' => 16, 'name' => 'Tulungagung'],

            //17. Provinsi Bali
            ['province_id' => 17, 'name' => 'Badung'],
            ['province_id' => 17, 'name' => 'Bangli'],
            ['province_id' => 17, 'name' => 'Buleleng'],
            ['province_id' => 17, 'name' => 'Denpasar'],
            ['province_id' => 17, 'name' => 'Gianyar'],
            ['province_id' => 17, 'name' => 'Jembrana'],
            ['province_id' => 17, 'name' => 'Karangasem'],
            ['province_id' => 17, 'name' => 'Klungkung'],
            ['province_id' => 17, 'name' => 'Tabanan'],

            //18. Provinsi Nusa Tenggara Barat (NTB)
            ['province_id' => 18, 'name' => 'Bima'],
            ['province_id' => 18, 'name' => 'Dompu'],
            ['province_id' => 18, 'name' => 'Lombok Barat'],
            ['province_id' => 18, 'name' => 'Lombok Tengah'],
            ['province_id' => 18, 'name' => 'Lombok Timur'],
            ['province_id' => 18, 'name' => 'Lombok Utara'],
            ['province_id' => 18, 'name' => 'Mataram'],
            ['province_id' => 18, 'name' => 'Sumbawa'],
            ['province_id' => 18, 'name' => 'Sumbawa Barat'],

            //19. Provinsi Nusa Tenggara Timur (NTT)
            ['province_id' => 19, 'name' => 'Alor'],
            ['province_id' => 19, 'name' => 'Belu'],
            ['province_id' => 19, 'name' => 'Ende'],
            ['province_id' => 19, 'name' => 'Flores Timur'],
            ['province_id' => 19, 'name' => 'Kupang'],
            ['province_id' => 19, 'name' => 'Lembata'],
            ['province_id' => 19, 'name' => 'Malaka'],
            ['province_id' => 19, 'name' => 'Manggarai'],
            ['province_id' => 19, 'name' => 'Manggarai Barat'],
            ['province_id' => 19, 'name' => 'Manggarai Timur'],
            ['province_id' => 19, 'name' => 'Nagekeo'],
            ['province_id' => 19, 'name' => 'Ngada'],
            ['province_id' => 19, 'name' => 'Rote Ndao'],
            ['province_id' => 19, 'name' => 'Sabu Raijua'],
            ['province_id' => 19, 'name' => 'Sikka'],
            ['province_id' => 19, 'name' => 'Sumba Barat'],
            ['province_id' => 19, 'name' => 'Sumba Barat Daya'],
            ['province_id' => 19, 'name' => 'Sumba Tengah'],
            ['province_id' => 19, 'name' => 'Sumba Timur'],
            ['province_id' => 19, 'name' => 'Timor Tengah Selatan'],
            ['province_id' => 19, 'name' => 'Timor Tengah Utara'],

            //20. Provinsi Kalimantan Barat
            ['province_id' => 20, 'name' => 'Bengkayang'],
            ['province_id' => 20, 'name' => 'Kapuas Hulu'],
            ['province_id' => 20, 'name' => 'Kayong Utara'],
            ['province_id' => 20, 'name' => 'Ketapang'],
            ['province_id' => 20, 'name' => 'Kubu Raya'],
            ['province_id' => 20, 'name' => 'Landak'],
            ['province_id' => 20, 'name' => 'Melawi'],
            ['province_id' => 20, 'name' => 'Mempawah'],
            ['province_id' => 20, 'name' => 'Pontianak'],
            ['province_id' => 20, 'name' => 'Sambas'],
            ['province_id' => 20, 'name' => 'Sanggau'],
            ['province_id' => 20, 'name' => 'Sekadau'],
            ['province_id' => 20, 'name' => 'Singkawang'],
            ['province_id' => 20, 'name' => 'Sintang'],

            //21. Provinsi Kalimantan Tengah
            ['province_id' => 21, 'name' => 'Barito Selatan'],
            ['province_id' => 21, 'name' => 'Barito Timur'],
            ['province_id' => 21, 'name' => 'Barito Utara'],
            ['province_id' => 21, 'name' => 'Gunung Mas'],
            ['province_id' => 21, 'name' => 'Kapuas'],
            ['province_id' => 21, 'name' => 'Katingan'],
            ['province_id' => 21, 'name' => 'Kotawaringin Barat'],
            ['province_id' => 21, 'name' => 'Kotawaringin Timur'],
            ['province_id' => 21, 'name' => 'Lamandau'],
            ['province_id' => 21, 'name' => 'Murung Raya'],
            ['province_id' => 21, 'name' => 'Palangka Raya'],
            ['province_id' => 21, 'name' => 'Pulang Pisau'],
            ['province_id' => 21, 'name' => 'Sukamara'],
            ['province_id' => 21, 'name' => 'Seruyan'],

            //22. Provinsi Kalimantan Selatan
            ['province_id' => 22, 'name' => 'Balangan'],
            ['province_id' => 22, 'name' => 'Banjar'],
            ['province_id' => 22, 'name' => 'Banjarbaru'],
            ['province_id' => 22, 'name' => 'Banjarmasin'],
            ['province_id' => 22, 'name' => 'Barito Kuala'],
            ['province_id' => 22, 'name' => 'Hulu Sungai Selatan'],
            ['province_id' => 22, 'name' => 'Hulu Sungai Tengah'],
            ['province_id' => 22, 'name' => 'Hulu Sungai Utara'],
            ['province_id' => 22, 'name' => 'Kotabaru'],
            ['province_id' => 22, 'name' => 'Tabalong'],
            ['province_id' => 22, 'name' => 'Tanah Bumbu'],
            ['province_id' => 22, 'name' => 'Tanah Laut'],
            ['province_id' => 22, 'name' => 'Tapin'],

            //23. Provinsi Kalimantan Timur
            ['province_id' => 23, 'name' => 'Balikpapan'],
            ['province_id' => 23, 'name' => 'Berau'],
            ['province_id' => 23, 'name' => 'Bontang'],
            ['province_id' => 23, 'name' => 'Kutai Barat'],
            ['province_id' => 23, 'name' => 'Kutai Kartanegara'],
            ['province_id' => 23, 'name' => 'Kutai Timur'],
            ['province_id' => 23, 'name' => 'Mahakam Ulu'],
            ['province_id' => 23, 'name' => 'Paser'],
            ['province_id' => 23, 'name' => 'Penajam Paser Utara'],
            ['province_id' => 23, 'name' => 'Samarinda'],

            //24. Provinsi Kalimantan Utara
            ['province_id' => 24, 'name' => 'Bulungan'],
            ['province_id' => 24, 'name' => 'Malinau'],
            ['province_id' => 24, 'name' => 'Nunukan'],
            ['province_id' => 24, 'name' => 'Tanjung Selor'],
            ['province_id' => 24, 'name' => 'Tarakan'],
            ['province_id' => 24, 'name' => 'Tana Tidung'],

            //25. Provinsi Sulawesi Utara
            ['province_id' => 25, 'name' => 'Bitung'],
            ['province_id' => 25, 'name' => 'Bolaang Mongondow'],
            ['province_id' => 25, 'name' => 'Bolaang Mongondow Selatan'],
            ['province_id' => 25, 'name' => 'Bolaang Mongondow Timur'],
            ['province_id' => 25, 'name' => 'Bolaang Mongondow Utara'],
            ['province_id' => 25, 'name' => 'Kepulauan Sangihe'],
            ['province_id' => 25, 'name' => 'Kepulauan Siau Tagulandang Biaro (Sitaro)'],
            ['province_id' => 25, 'name' => 'Kepulauan Talaud'],
            ['province_id' => 25, 'name' => 'Kotamobagu'],
            ['province_id' => 25, 'name' => 'Manado'],
            ['province_id' => 25, 'name' => 'Minahasa'],
            ['province_id' => 25, 'name' => 'Minahasa Selatan'],
            ['province_id' => 25, 'name' => 'Minahasa Tenggara'],
            ['province_id' => 25, 'name' => 'Minahasa Utara'],
            ['province_id' => 25, 'name' => 'Tomohon'],

            //26. Provinsi Gorontalo
            ['province_id' => 26, 'name' => 'Boalemo'],
            ['province_id' => 26, 'name' => 'Bone Bolango'],
            ['province_id' => 26, 'name' => 'Gorontalo'],
            ['province_id' => 26, 'name' => 'Gorontalo Utara'],
            ['province_id' => 26, 'name' => 'Pohuwato'],

            //27. Provinsi Sulawesi Tengah
            ['province_id' => 27, 'name' => 'Banggai'],
            ['province_id' => 27, 'name' => 'Banggai Kepulauan'],
            ['province_id' => 27, 'name' => 'Banggai Laut'],
            ['province_id' => 27, 'name' => 'Buol'],
            ['province_id' => 27, 'name' => 'Donggala'],
            ['province_id' => 27, 'name' => 'Morowali'],
            ['province_id' => 27, 'name' => 'Morowali Utara'],
            ['province_id' => 27, 'name' => 'Palu'],
            ['province_id' => 27, 'name' => 'Parigi Moutong'],
            ['province_id' => 27, 'name' => 'Poso'],
            ['province_id' => 27, 'name' => 'Sigi'],
            ['province_id' => 27, 'name' => 'Tojo Una-Una'],
            ['province_id' => 27, 'name' => 'Tolitoli'],

            //28. Provinsi Sulawesi Barat
            ['province_id' => 28, 'name' => 'Majene'],
            ['province_id' => 28, 'name' => 'Mamasa'],
            ['province_id' => 28, 'name' => 'Mamuju'],
            ['province_id' => 28, 'name' => 'Mamuju Tengah'],
            ['province_id' => 28, 'name' => 'Pasangkayu'],

            //29. Provinsi Sulawesi Selatan
            ['province_id' => 29, 'name' => 'Bantaeng'],
            ['province_id' => 29, 'name' => 'Barru'],
            ['province_id' => 29, 'name' => 'Bone'],
            ['province_id' => 29, 'name' => 'Bulukumba'],
            ['province_id' => 29, 'name' => 'Enrekang'],
            ['province_id' => 29, 'name' => 'Gowa'],
            ['province_id' => 29, 'name' => 'Jeneponto'],
            ['province_id' => 29, 'name' => 'Kepulauan Selayar'],
            ['province_id' => 29, 'name' => 'Luwu'],
            ['province_id' => 29, 'name' => 'Luwu Timur'],
            ['province_id' => 29, 'name' => 'Luwu Utara'],
            ['province_id' => 29, 'name' => 'Makassar'],
            ['province_id' => 29, 'name' => 'Maros'],
            ['province_id' => 29, 'name' => 'Palopo'],
            ['province_id' => 29, 'name' => 'Pangkajene dan Kepulauan'],
            ['province_id' => 29, 'name' => 'Parepare'],
            ['province_id' => 29, 'name' => 'Pinrang'],
            ['province_id' => 29, 'name' => 'Sidenreng Rappang'],
            ['province_id' => 29, 'name' => 'Sinjai'],
            ['province_id' => 29, 'name' => 'Soppeng'],
            ['province_id' => 29, 'name' => 'Takalar'],
            ['province_id' => 29, 'name' => 'Tana Toraja'],
            ['province_id' => 29, 'name' => 'Toraja Utara'],
            ['province_id' => 29, 'name' => 'Wajo'],

            //30. Provinsi Sulawesi Tenggara
            ['province_id' => 30, 'name' => 'Baubau'],
            ['province_id' => 30, 'name' => 'Bombana'],
            ['province_id' => 30, 'name' => 'Buton'],
            ['province_id' => 30, 'name' => 'Buton Selatan'],
            ['province_id' => 30, 'name' => 'Buton Tengah'],
            ['province_id' => 30, 'name' => 'Buton Utara'],
            ['province_id' => 30, 'name' => 'Kendari'],
            ['province_id' => 30, 'name' => 'Kolaka'],
            ['province_id' => 30, 'name' => 'Kolaka Timur'],
            ['province_id' => 30, 'name' => 'Kolaka Utara'],
            ['province_id' => 30, 'name' => 'Konawe'],
            ['province_id' => 30, 'name' => 'Konawe Kepulauan'],
            ['province_id' => 30, 'name' => 'Konawe Selatan'],
            ['province_id' => 30, 'name' => 'Konawe Utara'],
            ['province_id' => 30, 'name' => 'Muna'],
            ['province_id' => 30, 'name' => 'Muna Barat'],
            ['province_id' => 30, 'name' => 'Wakatobi'],

            //31. Provinsi Maluku
            ['province_id' => 31, 'name' => 'Ambon'],
            ['province_id' => 31, 'name' => 'Buru'],
            ['province_id' => 31, 'name' => 'Buru Selatan'],
            ['province_id' => 31, 'name' => 'Kepulauan Aru'],
            ['province_id' => 31, 'name' => 'Kepulauan Tanimbar'],
            ['province_id' => 31, 'name' => 'Maluku Barat Daya'],
            ['province_id' => 31, 'name' => 'Maluku Tengah'],
            ['province_id' => 31, 'name' => 'Maluku Tenggara'],
            ['province_id' => 31, 'name' => 'Seram Bagian Barat'],
            ['province_id' => 31, 'name' => 'Seram Bagian Timur'],
            ['province_id' => 31, 'name' => 'Tual'],

            //32. Provinsi Maluku Utara
            ['province_id' => 32, 'name' => 'Halmahera Barat'],
            ['province_id' => 32, 'name' => 'Halmahera Tengah'],
            ['province_id' => 32, 'name' => 'Halmahera Timur'],
            ['province_id' => 32, 'name' => 'Halmahera Selatan'],
            ['province_id' => 32, 'name' => 'Halmahera Utara'],
            ['province_id' => 32, 'name' => 'Kepulauan Sula'],
            ['province_id' => 32, 'name' => 'Pulau Morotai'],
            ['province_id' => 32, 'name' => 'Pulau Taliabu'],
            ['province_id' => 32, 'name' => 'Sofifi'],
            ['province_id' => 32, 'name' => 'Ternate'],
            ['province_id' => 32, 'name' => 'Tidore Kepulauan'],

            //33. Provinsi Papua Barat
            ['province_id' => 33, 'name' => 'Fakfak'],
            ['province_id' => 33, 'name' => 'Kaimana'],
            ['province_id' => 33, 'name' => 'Manokwari'],
            ['province_id' => 33, 'name' => 'Manokwari Selatan'],
            ['province_id' => 33, 'name' => 'Pegunungan Arfak'],
            ['province_id' => 33, 'name' => 'Teluk Bintuni'],
            ['province_id' => 33, 'name' => 'Teluk Wondama'],

            //34. Provinsi Papua
            ['province_id' => 34, 'name' => 'Biak Numfor'],
            ['province_id' => 34, 'name' => 'Jayapura'],
            ['province_id' => 34, 'name' => 'Keerom'],
            ['province_id' => 34, 'name' => 'Kepulauan Yapen'],
            ['province_id' => 34, 'name' => 'Mamberamo Raya'],
            ['province_id' => 34, 'name' => 'Sarmi'],
            ['province_id' => 34, 'name' => 'Supiori'],
            ['province_id' => 34, 'name' => 'Waropen'],

            //35. Provinsi Papua Selatan
            ['province_id' => 35, 'name' => 'Asmat'],
            ['province_id' => 35, 'name' => 'Boven Digoel'],
            ['province_id' => 35, 'name' => 'Mappi'],
            ['province_id' => 35, 'name' => 'Merauke'],

            //36. Provinsi Papua Tengah
            ['province_id' => 36, 'name' => 'Deiyai'],
            ['province_id' => 36, 'name' => 'Dogiyai'],
            ['province_id' => 36, 'name' => 'Intan Jaya'],
            ['province_id' => 36, 'name' => 'Mimika'],
            ['province_id' => 36, 'name' => 'Nabire'],
            ['province_id' => 36, 'name' => 'Paniai'],
            ['province_id' => 36, 'name' => 'Puncak'],
            ['province_id' => 36, 'name' => 'Puncak Jaya'],

            //37. Provinsi Papua Pegunungan
            ['province_id' => 37, 'name' => 'Jayawijaya'],
            ['province_id' => 37, 'name' => 'Lanny Jaya'],
            ['province_id' => 37, 'name' => 'Mamberamo Tengah'],
            ['province_id' => 37, 'name' => 'Nduga'],
            ['province_id' => 37, 'name' => 'Pegunungan Bintang'],
            ['province_id' => 37, 'name' => 'Tolikara'],
            ['province_id' => 37, 'name' => 'Yahukimo'],
            ['province_id' => 37, 'name' => 'Yalimo'],

            //38 Provinsi Papua Barat Daya
            ['province_id' => 38, 'name' => 'Maybrat'],
            ['province_id' => 38, 'name' => 'Raja Ampat'],
            ['province_id' => 38, 'name' => 'Sorong'],
            ['province_id' => 38, 'name' => 'Sorong Selatan'],
            ['province_id' => 38, 'name' => 'Tambrauw'],
            ['province_id' => 38, 'name' => 'Tual'],

        ];

        // Insert batch untuk efisiensi
        foreach (array_chunk($cities, 100) as $chunk) {
            DB::table('cities')->insert($chunk);
        }
    }
}
